### ISSUE TITLE
Update of "Datadog::Dashboards::Dashboard" resource fails

### ISSUE THREAD

**Issue by rickard-andersson-wcar** [DataDog/datadog-cloudformation-resources#127]
**Describe the bug**
We have a CloudFormation stack including one `Datadog::Dashboards::Dashboard` resource. When we first deploy the stack, the dashboard is created successfully. However, if we deploy the same stack again (even without any changes), the `Datadog::Dashboards::Dashboard` resource fails to update with error message: `'dict' object has no attribute '_composed_schemas'`.

The resource we're trying to update:
```yaml
OurDashboardResource:
    Type: Datadog::Dashboards::Dashboard
    Properties:
      DashboardDefinition: !Sub |
        {
          "title": "Title of Dashboard",
          "description": "",
          "widgets": [
            {
              "id": 12345,
              "definition": {
                ...definition of widget
              }
            }
          ],
          "template_variables": [],
          "layout_type": "ordered",
          "is_read_only": false,
          "notify_list": [],
          "id": "some-id"
        }
      DatadogCredentials:
        ApiKey: ##API-KEY##
        ApplicationKey: ##APPLICATION-KEY##
        ApiURL: https://api.datadoghq.eu
```

**To Reproduce**
1. Export an existing dashboard as json and include it as DashboardDefinition of a `Datadog::Dashboards::Dashboard` resource (similar to above code example)
2. Deploy the CloudFormation stack including the `Datadog::Dashboards::Dashboard` resource
3. Note that the resource was created successfully
4. Deploy the CloudFormation stack including the `Datadog::Dashboards::Dashboard` resource again
5. Note that the dashboard resource (and stack) fails to update due to: `'dict' object has no attribute '_composed_schemas'`.

**Logs**
`'dict' object has no attribute '_composed_schemas'`

**Expected behavior**
That the resource (and stack) updates successfully.

**Environment and Versions (please complete the following information):**
1.0.0
