### ISSUE TITLE
All monitors get created as "multi-alert"

### ISSUE THREAD

**Issue by techotron** [DataDog/datadog-cloudformation-resources#131]
**Describe the bug**
All monitors get created as multi-alert types, even when the `Multi: false` property is used. 

Label the issue properly.
- Add `severity/` label.
- Add `documentation` label if this issue is related to documentation changes.

**To Reproduce**
1. Use the following resource template to create a new monitor:
```
Resources:
  DatadogTestMonitor:
    Type: 'Datadog::Monitors::Monitor'
    Properties:
      Type: query alert
      Query: 'avg(last_1h):sum:system.cpu.system{host:host0} > 100'
      Name: Test Monitor
      Multi: false
      DatadogCredentials:
        ApiKey: <DD_API_KEY>
        ApplicationKey: <DD_APP_KEY>
```

2. Edit the monitor via the DD UI and the "Multi-Alert" is displayed in the drop down.

**Logs**
n/a

**Expected behavior**
The monitor is created with a "Simple-Alert" type instead.

**Screenshots**
n/a

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:
  - AWS CLI 2.2.1
I'm not sure how to check which template version we're using but resource type was last updated on 2020-07-07 so I assume it's `datadog-monitors-monitor-2.0.0`

**Additional context**
My Python skills are not as good as I'd like but it looks like the `groupby_simple_monitor` option isn't added in the  `build_monitor_options_from_model()` function [in the handler](https://github.com/DataDog/datadog-cloudformation-resources/blob/4288f3c5a806e04c385021c3ecb5232a496e5b30/datadog-monitors-monitor-handler/src/datadog_monitors_monitor/handlers.py#L253)

Perhaps this is just a case of adding `GroupbySimpleMonitor` to [the MonitorOptions dataclass](https://github.com/DataDog/datadog-cloudformation-resources/blob/4288f3c5a806e04c385021c3ecb5232a496e5b30/datadog-monitors-monitor-handler/src/datadog_monitors_monitor/models.py#L135) and then adding a negation when setting the option in `build_monitor_options_from_model()`:

```
        if model.Options.GroupbySimpleMonitor is not None:
            options.groupby_simple_monitor = not model.Options.GroupbySimpleMonitor
```

If it looks like my assumptions are along the right track I can submit a PR but like I said, my Python skills aren't strong so I could be way off :)
