### ISSUE TITLE
After upgrade to 4.0.0 get error "extraneous key [DatadogCredentials] is not permitted"

### ISSUE THREAD

**Issue by sunshineo** [DataDog/datadog-cloudformation-resources#158]
We are using serverless, here is our yml
```
resources:
  Resources:
    DatadogMonitorP1:
      Type: Datadog::Monitors::Monitor
      Properties:
        Type: log alert
        Query: 'logs("service:${self:service} env:${env:CI_COMMIT_BRANCH} status:error").index("main").rollup("count").last("1h") > 100'
        Name: ${self:service}-${env:CI_COMMIT_BRANCH}-p1
        Message: '{{#is_alert}} ALERT! {{event.text}} {{/is_alert}} ${self:custom.datadogP1.${env:CI_COMMIT_BRANCH}}'
        DatadogCredentials:
          ApiKey: ${self:custom.datadogSecrets.apiKey}
          ApplicationKey: ${self:custom.datadogSecrets.applicationKey}
```
What is the new way to do this? I did not find any documentation
