### ISSUE TITLE
Internal error with empty message when deploying

### ISSUE THREAD

**Issue by OzoTek** [DataDog/datadog-cloudformation-resources#202]
**Describe the bug**

I am currently trying to deploy monitors (`Datadog::Monitors::Monitor`) and am getting an Internal Error with an empty message (I've tried with a dashboard and get the same issue):
> Resource handler returned message: "" (RequestToken: 46b52e64-453a-a516-2be4-547868e0bc6f, HandlerErrorCode: InternalFailure)

<details>
  <summary>Here's the template I'm trying to deploy:</summary>

  ```yaml
Resources:
  ThroughputMonitor:
    Type: Datadog::Monitors::Monitor
    Properties:
      Type: query alert
      Name: Service xxx has an abnormal change in throughput on env:prod
      Query: avg(last_4h):anomalies(sum:trace.express.request.hits{env:prod,service:xxx}, 'agile', 3, direction='both', interval=60, alert_window='last_15m', seasonality='weekly', timezone='utc', count_default_zero='true') >= 1
      Message: "`xxx` throughput deviated too much from its usual value."
      Tags:
        - service:xxx
        - env:prod
      Priority: 2
      Modified: "2022-03-29T13:15:48.646Z"
      Options:
        Thresholds:
          Critical: 1
          CriticalRecovery: 0
        NotifyAudit: false
        RequireFullWindow: false
        NotifyNoData: false
        RenotifyInterval: 0
        ThresholdWindows:
          TriggerWindow: last_15m
          RecoveryWindow: last_15m
        IncludeTags: true
        EnableLogsSample: true
    Metadata:
      aws:cdk:path: DatadogMonitorsStack/ThroughputMonitor
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zPUMzQx1jNQdEgsL9ZNTsnWT84vStWrDi5JTM7WcU7LC0otzi8tSk7Vcc7PKy4pKk0uAYkCOSmZJZn5ebU6efkpqXpZxfplhmZAo4AmZRVnZuoWleaVZOam6gVBaABHq3UgZgAAAA==
    Metadata:
      aws:cdk:path: DatadogMonitorsStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
```
</details>

**To Reproduce**
Unfortunately, we're having this issue only with a specific AWS account. The same template deploys just fine on other accounts. The strange thing is, it is not different than any other account in the sense that all the necessary components and accesses are setup the same way. This is controlled by a single account and Control Tower and is applied to all the other accounts.

**Logs**
Our problem is actually the lack of logs. The error is empty. We receive the correct errors if we make a syntax or semantic error, but for a valid template like the one linked, the error message is not provided.

**Expected behavior**
A descriptive error message is provided to help pinpoint issues in the setup.

**Environment and Versions (please complete the following information):**
  - Deployed using cdk 2.17.0
  - Datadog Monitor 4.2.0
