### ISSUE TITLE
Datadog::Monitors::Monitor Query case mismatch

### ISSUE THREAD

**Issue by JayFields** [DataDog/datadog-cloudformation-resources#235]
Referencing a lambda ARN in a SAM template may result in an ARN that contains uppercase characters. However, a Datadog log alert monitor query only uses lowercase characters. Therefore the query produced by referencing a lambda ARN will never match the lowercased ARN in Datadog. There isn't an easy way to make a string lowercase in SAM, so I think Datadog::Monitors::Monitor should handle this.

**To Reproduce**
1. Create a lambda monitored by Datadog:

```
MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: My test function
      CodeUri: lambdas/my_function
      Handler: app.lambda_handler
      Runtime: python3.9

  MyFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${MyFunction}

  MyFunctionLogGroupSubscription:
    Type: AWS::Logs::SubscriptionFilter
    DependsOn: MyFunctionLogGroup
    Properties:
      DestinationArn:
        Fn::ImportValue:
          !Sub ${DatadogStack}:DatadogDeliveryStreamARN
      LogGroupName: !Sub /aws/lambda/${MyFunction}
      RoleArn:
        Fn::ImportValue:
          !Sub ${DatadogStack}:CloudWatchLogsRoleARN
      FilterPattern: ""

MyFunctionMonitor:
    Type: Datadog::Monitors::Monitor
    Properties:
      Type: log alert
      Query: !Sub 'logs("host:\"${MyFunction.Arn}\"").index("*").rollup("count").last("3h") < 1'
      Name: My Function Monitor
```

2. Generate some logs in the MyFunction lambda
3. Go to the My Function Monitor in datadog
4. Notice that there are no matching logs in the monitor. The reason for this is that `!Sub ${MyFunction.Arn}` produces an ARN in SAM like this `arn:aws:lambda:us-east-1:123456789012:function:MyFunction-aBcdeOZ5Ug1c` but Datadog is looking for an all lowercase version like this `arn:aws:lambda:us-east-1:123456789012:function:myfunction-abcdeoz5ug1c`. Datadog::Monitors::Monitor does not convert the ARN in the query to lowercase.

**Expected behavior**
Datadog::Monitors::Monitor to produce a working monitor regardless of the input case of the ARN 

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:
  - SAM CLI, version 1.61.0
