### ISSUE TITLE
Add Dashboard api support

### ISSUE THREAD

**Issue by rjcoelho** [DataDog/datadog-cloudformation-resources#75]

**Comment by nmuesch** [comment]
Hey @rjcoelho We just released an initial beta version of the dashboard resource here https://github.com/DataDog/datadog-cloudformation-resources/releases/tag/datadog-dashboards-dashboard-1.0.0b1 Can you give that a try and see if it addresses your use case?

**Comment by dirkraft** [comment]
Hello I stumbled across this and gave it a try. Copied that zip to my own bucket. Redacted some private stuff below with `...`

```
$ aws cloudformation register-type --type RESOURCE --type-name Datadog::Dashboards::Dashboard --schema-handler-package s3://.../datadog-dashboards-dashboard-1.0.0b1.zip
{
    "RegistrationToken": "dc0f2643-fab5-4976-9059-b7a8cd548747"
}

# after a while...
$ aws cloudformation describe-type-registration --registration-token dc0f2643-fab5-4976-9059-b7a8cd548747
{
    "ProgressStatus": "COMPLETE",
    "Description": "Deployment is currently in DEPLOY_STAGE of status COMPLETED; ",
    "TypeArn": "arn:aws:cloudformation:us-west-2:...:type/resource/Datadog-Dashboards-Dashboard",
    "TypeVersionArn": "arn:aws:cloudformation:us-west-2:...:type/resource/Datadog-Dashboards-Dashboard/00000002"
}
```

Tried to create minimal stack, stack.yaml
```yaml
Resources:
  DatadogTestDashboard:
    Type: 'Datadog::Dashboards::Dashboard'
    Properties:
      DashboardDefinition: |
        {"title":"jason blank","description":"","widgets":[],"template_variables":[],"layout_type":"ordered","is_read_only":false,"notify_list":[],"id":"tmm-hyc-dbw"}
      DatadogCredentials:
        ApiURL: https://api.datadoghq.com
        ApiKey: ...
        ApplicationKey: ...
```

command line
```
$ aws cloudformation create-stack --stack-name jason-dd-test2 --template-body file://stack.yaml
```

console
<img width="1479" alt="Screen Shot 2020-11-10 at 12 20 30 PM" src="https://user-images.githubusercontent.com/487920/98729028-22e8c200-234f-11eb-934d-b9108c142d18.png">
